# Generated by Django 2.2.5 on 2019-12-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='Tiaret', max_length=20),
            preserve_default=False,
        ),
    ]
