# Generated by Django 2.2.5 on 2019-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_profile_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(choices=[('plumber', 'Pulmber'), ('welder', 'Welder'), ('maneuver', 'Maneuver'), ('builder', 'Builder'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mover', 'Mover'), ('exterminator', 'Exterminator')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('Occupé', 'occupé'), ('Libre', 'libre')], max_length=20),
        ),
    ]
